### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by BBDrive** [dosssman/GymTorcs#2]
Suddenly a new problem appears.
When I run the basic code:
```import gym

# Gym Torcs dep.
import gym_torcs

try:
  # Instantiate the environment
  env = gym.make( "Torcs-v0")

  o ,r, done = env.reset(), 0., False
  while not done:
    action = np.tanh(np.random.randn(env.action_space.shape[0]))
    o, r, done, _ = env.step( action)

except Execption as e:
  print( e)

finally:
  env.end()
```

a new problem appears.
```Compatibility mode, properties unknown.
Waiting for request on port 3000
Waiting for server on 3000............
Count Down : 5
Client connected on 3000..............
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such device or address
terminate called after throwing an instance of 'char const*'
/usr/local/bin/torcs: line 53: 33375 Aborted                 (core dumped) $LIBDIR/torcs-bin -l $LOCAL_CONF -L $LIBDIR -D $DATADIR $*
```

**Comment by dosssman** [comment]
It seems that you have changed your configuration or the machine you are running it on.
Although it is not necessary for our purposes, Torcs still requires a sound device to be able to work.

First, try to check that you have audio engine such as pulseaudio or alsa installed. If despite doing that it does not work,

the workaround I found when I briefly had this issue was to install the `oss` or `ossdp` package (can't exactly remember which on), then I would run it using `padsp python main.py` for example.
Here was the source of the trick: https://ubuntuforums.org/showthread.php?t=2173702

**Comment by BBDrive** [comment]
When I run it using `padsp python main.py`, it is ok.
Another question: 
I run `padsp torcs -raceconfig $pwd/human_10fixed_sparse_2.xml -rechum 0 -rectimesteplim 3600`, but i can't control the car and don't collect any data.

**Comment by BBDrive** [comment]
When I use absolute path, `torcs -raceconfig /home/dragon/player_data/human_10fixed_sparse_2.xml -rechum 0 -rectimesteplim 3600`, it shows
```
Recording first player 's dataVisual Properties Report
------------------------
Compatibility mode, properties unknown.
#### DEBUG: Initializing save paths
/usr/local/bin/torcs: line 53:  5832 Segmentation fault      (core dumped) $LIBDIR/torcs-bin -l $LOCAL_CONF -L $LIBDIR -D $DATADIR $*
```

**Comment by dosssman** [comment]
Please set the environment variable as follows: `export TORCS_DATA_DIR=/home/dragon/player_data` so the binary of Torcs can recognize it.

**Comment by BBDrive** [comment]
I set the environment variable and i can collect the data, but i can't control the vehicle.

**Comment by dosssman** [comment]
Controls can be set by first running the `torcs` or `padsp torcs` command then accessing menu.

**Comment by BBDrive** [comment]
There seems to be no control options in the menu.

**Comment by dosssman** [comment]
Configure Players -> Click on Players -> Then click on Controls ...

**Comment by BBDrive** [comment]
when i click `Configure Players`，it shows error.
```
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
/usr/local/bin/torcs: line 53:  3916 Segmentation fault      (core dumped) $LIBDIR/torcs-bin -l $LOCAL_CONF -L $LIBDIR -D $DATADIR $*
```

**Comment by dosssman** [comment]
Unfortunately, this error is outside of my range of knowledge on Torcs. Sorry.

**Comment by BBDrive** [comment]
That's nothing. Have you encountered a similar problem？

**Comment by dosssman** [comment]
No. Not when trying to configure the controls.

**Comment by dosssman** [comment]
Just tried on my side and it still works.

**Comment by BBDrive** [comment]
OK. Thanks for your kind answer.

**Comment by dosssman** [comment]
Actually, I might have an idea of what is causing it.
Turns out Torcs was not able to find the configuration files by default when I was using it, so I had to hard code the path to the XML config file it reads for the settings, among which the controls.

You will need to edit 2 files in the `gym_torqs/vtorcs-RL-colors` that was installed by the dependency script.

The first one is `vtorcs-RL-colors/src/interfaces/graphic.h`. Please change the `/home/z3r0/` to your own user home directory around line 31, namely:
```
#define GR_PARAM_FILE		"/home/z3r0/.torcs/config/graph.xml"
```
The second file is `vtorcs-RL-colors/src/inferfaces/playerpref.h`. You will also have to change `/home/z3r0` at 2 locations,  in the interval of lines 28 to 33
```
#define HM_DRV_FILE  		"/home/z3r0/.torcs/drivers/human/human.xml"
// dossman edit because Torcs couldn't autopmatically find the file
// #define HM_PREF_FILE		"drivers/human/preferences.xml"
#define HM_PREF_FILE		"/home/z3r0/.torcs/drivers/human/preferences.xml"
```
I left the default configuration, so you might want to give it a try if you are in a debugging mood, otherwise, hardcoding is what made it work for me.

Once you have made the edits, please **recompile** the vtorcs-RL-colors as in the install script.
Hopefully, it will work.

**Comment by dosssman** [comment]
In retrospect, I think the Torcs binary expects to find the configuration files in the running directory, but since most of the time I did not run the scripts from the home directory, but that of the reinforcement learning project itself, it was failing, which then made me hardcode the path to the config files so it would work from anywhere.

There was probably a more elegant solution hahaha.

**Comment by BBDrive** [comment]
Wow. It works very well. I admire you a lot.

**Comment by dosssman** [comment]
Thanks for the kind words.
I hope I can live up to your expectations one day.

**Comment by BBDrive** [comment]
Hi, i have a question.
When I record the data, I found that the parameter of `rpm` normalization of [obs += SimpleParser::stringifym( car->_enginerpm / 1000);](https://github.com/dosssman/gym_torqs/blob/dd7426bee5a62281b263e4e1d9b36e7721ce61e5/vtorcs-RL-color/src/libs/raceengineclient/racestate.cpp#L508)  and ['rpm': 10000.](https://github.com/dosssman/GymTorcs/blob/53f4440b55cf44fc03120fb61a2d56f55de14922/gym_torcs/torcs_env.py#L56) are different.
1. Is the parameter of rpm normalized wrong?
2. Are other parameters normalized correctly? I think it should be.

**Comment by dosssman** [comment]
Nice catch. The normalization values should indeed match across the `racestate.cpp` file and the `TorcsEnv` wrapper.
I have checked to make sure the other normalization values are correct.

On an aside, please note that the specific value for the `rpm` normalization` was determined empirically during my experiments.
Therefore, the RPM might take values that are not appropriate fro that `10000` used for normalization.
The maximum value I would get with an agent driving at full speed was around 7000, so I set it to 10000 just to be sure it stays bounded within 0 and 1. But overall, that parameter was mostly ignored by the neural networks I think.
