### ISSUE TITLE
Running Error.

### ISSUE THREAD

**Issue by huoliangyu** [dosssman/GymTorcs#3]
Nice work!
I followed the instruction and run deps_install_script.sh. Still, I have the following questions. Any kind help would be greatly appreciated.
1. I can successfully run like gym.make("Torcs-v0"). The window of Torcs startup, but I cannot see anything but black.
2. Do those demo codes such as a2c.py in gym_torqs work? If so, it will be a good start point to use.
3. Could you please provide some basic training curves or scores as baseline with which we are able to figure out whether  our agent are effectively trained.
4. Since the continuous action space is more difficult to train, do you have any idea to convert this env to discrete action space.

**Comment by dosssman** [comment]
Greetings.
Sorry for the messy code.

1. Regarding the lack of rendering, you can enable it by passing the `vision` and `rendering` flags to the environment as follows: 
`env = gym.make( 'Torcs-v0', vision=True, rendering=True, obs_preprocess_fn=obs_preprocess_fn)`

2. The A2C scripts were very experimental code, and I would not really recommend it as a starting point. A better starting point I know will at least work would be the DDPG agent hosted here: https://github.com/dosssman/TorcsRLILHybrid .
That is the project the GymTorcs wrapped was original conceived for. 
The DDPG agent itself is based on openai/baselines, and uses Tensorflow 1.1X

However, you can use the GymTorcs wrapper and combine it with openai/stable-baselines3, or openai/spinning and it should still work. I recommend the later since it has Pytorch code that is probaby easier to understand and customize than Tensorflow 1.1X, in case you do not have experience with the later already.

3.  I uploaded the Tensorboard log (zip file a below) of the DDPG agent from TorcsRLILHybrid as reference . I would usually track the "rollout" section in the tensorboard log:
![image](https://user-images.githubusercontent.com/21224272/131916357-11c8cbbf-95d6-483a-b106-4272e756d7d9.png)

[openai-ddpgtorcs-2018-12-05-13-20-33-056875.zip](https://github.com/dosssman/GymTorcs/files/7101838/openai-ddpgtorcs-2018-12-05-13-20-33-056875.zip)

You can extract the folder above, enter it and run `tensorboard --logdir .` to get a better idea yourself, and export the data in CSV or JSON if you want.

4. Yes. But the caveat is that you will have to engineer the action space to allow the agent to make moves that 'make sense'. For example, if we only have discrete actions of 'turn left', 'turn right', 'accelerate', etc...,the agent could not 'turn right and accelerate' at the same time, unless you manually design an action 'turn right and accelerate'. But then you would also have to design the action 'turn left and accelerate', etc...

Another problem is that in Torcs, the steering and acceleration are continuous for a finer control over the car.
For example, steering left of right corresponding to the ranges [-1,0) and (0, 1] respectively, so that the agent can choose how __strong__ the steering should. This would probably be harder to handle in a discrete case, as you would need to discretize the action of turn left into let's say "turn_left_1`, `turn_left_0.8`, 'turn_left_0.6`, etc..., which can result in a big action space.

In any case, an outline of a very simple way of doing it with the GymTorcs wrapper  would be to start [here](https://github.com/dosssman/GymTorcs/blob/53f4440b55cf44fc03120fb61a2d56f55de14922/gym_torcs/torcs_env.py#L148) and change the action space to something like
```python
self.action_space = spaces.Discrete(4)
```
to get actions likes: 0 -> forward, 1 -> turn left, 2 -> turn right, 3 -> backward (we rarely want the agent to go backward thorugh, so might as well do without this action ?).

Then [here](https://github.com/dosssman/GymTorcs/blob/53f4440b55cf44fc03120fb61a2d56f55de14922/gym_torcs/torcs_env.py#L574), we would need to add the logic to make the environment understand what each discrete action correponds to:
```python

def agent_to_torcs(self, u):
    # Since the action u is discrete, in {0,1,2,3}
    steer, action = 0., 0.
    
    # Again, please refer to my comment in 4. above, as this 
    # way action space will result in an `extreme` agent that likely zig zags
    if action == 0:
        accel = 1.
    elif action == 1:
        steer = -1.
    elif action == 2:
        steer = 1.
    elif action == 3:
         accel = -1. # negative accel is equivalent to first braking, then going backward

   torcs_action = {"steer": steer, "accel": accel}

    return torcs_action
```

Hope this help.
Best wishes for your experiments.

**Comment by huoliangyu** [comment]
@dosssman Hi~, thanks for your quick and detailed reply.  I use the code from TorcsRLILHybrid just as you recommended. In the current, I set the flag rendering== True and vision==False, i.e., `env=gym.make("Torcs-v0",rendering== True,vision==False,xxxxxxx)`, other parameters are kept default. This time, I can see the track but no cars. As the code is running, the  game screen moves correspondingly, but still nor cars. It seems like the model of the car was not loaded correctly？ Is there any possibility that I didn't install Torcs correctly?

**Comment by dosssman** [comment]
If I recall correctly, the simulator adopts a FPS view by default.
Press F2 while in game to cycle between the various view. You should be able to see the car of the agent.
Press F1 to have additional details on the controls in-games.

Hope this helps.

**Comment by huoliangyu** [comment]
Thanks for your replay. Indeed, F2 is the shortcut to switch the view. However, after pressing F2, the view changed but there is still no car on the screen, even if the view has changed in cycle. It just looks like everything seems to be working fine except for the car model. On the other hand, so far,  this minor problem has not affected the agent training. I would like to continue to try some other solutions. If you have any idea how to fix it or you meet a similar problem, please share the experience then. Thanks again for your replay and the useful project. I will do some experiments by this env, hope to communicate more with you.

**Comment by dosssman** [comment]
Glad to be of some help.

Maybe for some reason, the car model is not recognized.

I am not sure this is necessarily related, but I recall I had to hard code some user configuration path file which might influence the loading of the car model.
If you have some time, please chekout the following response: https://github.com/dosssman/GymTorcs/issues/2#issuecomment-651489409 which shows how to changing those hard coding settings.

Maybe a clean build of the Torcs simulator could fix it ?

Until then, best wishes for your experiments.
